# travis file for the broadbean package

language: python
python:
  - "3.5"

# Don't receive notifications for now
notifications:
  email: false

branches:
  only:
    - master

install: "pip install ."

# command sequence to run tests
script:
  - cd tests
  - pytest
